USE [Meu_Banco]
GO

/****** Object:  Table [dbo].[TPP]    Script Date: 03/03/2021 00:08:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TPP](
	[TPPCD] [int] IDENTITY(1,1) NOT NULL,
	[DESC] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[TPPCD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO TPP ("DESC") VALUES('CLIENTE');
INSERT INTO TPP ("DESC") VALUES('FUNCIONÁRIO');
INSERT INTO TPP ("DESC") VALUES('RESPONSÁVEL');

