USE [Meu_Banco]
GO

/****** Object:  Table [dbo].[SITP]    Script Date: 10/03/2021 23:40:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SITP](
	[SITPCD] [int] IDENTITY(1,1) NOT NULL,
	[DESC] [varchar](30) NULL,
PRIMARY KEY CLUSTERED 
(
	[SITPCD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO SITP ( "DESC") VALUES ('ATIVO');
INSERT INTO SITP ( "DESC") VALUES ('INATIVO');
INSERT INTO SITP ( "DESC") VALUES ('INADIMPLENTE');

